apiVersion: v1
kind: Service
metadata:
  name: activitymodder-backend
  labels:
    app: activitymodder
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: activitymodder
    tier: backend
  ports:
  - port: 80
    targetPort: http-server
