apiVersion: v1
kind: Service
metadata:
  name: acivitymodder-mongodb
  labels:
    app: activitymodder
    tier: db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: activitymodder
    tier: db
