apiVersion: v1
kind: Service
metadata:
  name: activitymodder-frontend
  labels:
    app: activitymodder
    tier: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 104.196.182.50
  selector:
    app: activitymodder
    tier: frontend
  ports:
  - port: 80
    targetPort: http-server
