apiVersion: apps/v1
kind: Deployment
metadata:
  name: activitymodder-postgres
spec:
  selector:
    matchLabels:
      app: activitymodder
  template:
    metadata:
      labels:
        app: activitymodder
    spec:
      containers:
      - name: postgres
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
